### ISSUE TITLE
Make name argument optional

### ISSUE THREAD

**Issue by paulrobertlloyd** [AndersDJohnson/base-create#1]
Thanks so much for putting this utility together, it makes creating an initializer script so much easier.

One thing that keeps tripping me up, and adds potential friction for end users, is the requirement to pass a name argument when running an initializer:

`npm create indiekit [name]`

If you don’t provide a name, the following error is returned:

```bash
/Users/paulrobertlloyd/Sites/indiekit/node_modules/base-create/index.js:126
  let packageDir = process.argv[2].replace(/\//g, "__");
                                   ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at createPackage (/Users/paulrobertlloyd/Sites/indiekit/node_modules/base-create/index.js:126:36)
    at create (/Users/paulrobertlloyd/Sites/indiekit/node_modules/base-create/index.js:235:18)
    at init (file:///Users/paulrobertlloyd/Sites/indiekit/packages/create-indiekit/index.js:53:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/paulrobertlloyd/Sites/indiekit/packages/create-indiekit/bin/create.js:8:1
```

## Options

There are possibly a few ways to resolve this:

1. Require a fallback name to be provided in `create()` options
2. Enable authors to provide a default name in `create()` options, and provide a default in the case that either no option provided in config, or no name argument provided (for example `package`)
3. Provide a helpful message asking the user to supply a name argument rather than throwing an error

**Comment by AndersDJohnson** [comment]
@paulrobertlloyd Good find, thanks for reporting! I like option 3 there as a first step. We could think about the other options as a possible follow up. Maybe the script could prompt to type a name on the command line. Anyway, would you be interested in submitting a PR to implement option 3?

**Comment by AndersDJohnson** [comment]
Maybe related but I think this may be a typo in the code - I don't think `node` is defined here: https://github.com/AndersDJohnson/base-create/blob/c40d26b7d1741598d42e1a3c119158c5e57ad22b/index.js#L136

**Comment by paulrobertlloyd** [comment]
> Would you be interested in submitting a PR to implement option 3?

Happy to!

> I don't think `node` is defined

Ah, this sounds like a bug than a feature request then! What might `node` be referring to? Might it be a component of `process.argv` (need to read up on how to parse command line entry, but if I remember correctly, it’s probably a value provided by that, isn’t it?)
